#!/bin/bash

# Hàm tạo địa chỉ IPv6 ngẫu nhiên với địa chỉ IPv6 cơ bản và 4 phần số ngẫu nhiên cho phần cuối
gen_ipv6_64() {
    ipv6_base="2403:6a40:0:1"  # Địa chỉ IPv6 cơ bản
    output_file="/home/ipv6.txt"  # Tên tệp xuất

    for ((i = 1; i <= 5000; i++)); do
        echo "$ipv6_base:$(printf "%04x:%04x:%04x:%04x" $((RANDOM % 65536)) $((RANDOM % 65536)) $((RANDOM % 65536)) $((RANDOM % 65536)))" >> "$output_file"
    done
}

gen_ipv6_64
